routes/web.php
        Route::put('/prestasi/{id}', [\App\Http\Controllers\PrestasiController::class, 'update'])->name('prestasi.update');
        Route::delete('/prestasi/{id}', [\App\Http\Controllers\PrestasiController::class, 'destroy'])->name('prestasi.destroy');

        Route::resource('/pengumuman', \App\Http\Controllers\PengumumanController::class);
        Route::get('/pengumuman', [\App\Http\Controllers\PengumumanController::class, 'index'])->name('pengumuman.index');
        Route::get('/pengumuman/create', [\App\Http\Controllers\PengumumanController::class, 'create'])->name('pengumuman.create');
        Route::post('/pengumuman', [\App\Http\Controllers\PengumumanController::class, 'store'])->name('pengumuman.store');
        Route::get('/pengumuman/{id}/edit', [\App\Http\Controllers\PengumumanController::class, 'edit'])->name('pengumuman.edit');
        Route::put('/pengumuman/{id}', [\App\Http\Controllers\PengumumanController::class, 'update'])->name('pengumuman.update');
        Route::delete('/pengumuman/{id}', [\App\Http\Controllers\PengumumanController::class, 'destroy'])->name('pengumuman.destroy');

        Route::resource('/galeri', \App\Http\Controllers\GaleriController::class);
        Route::get('/galeri', [\App\Http\Controllers\GaleriController::class, 'index'])->name('galeri.index');
        Route::get('/galeri/create', [\App\Http\Controllers\GaleriController::class, 'create'])->name('galeri.create');
        Route::post('/galeri', [\App\Http\Controllers\GaleriController::class, 'store'])->name('galeri.store');
        Route::get('/galeri/{id}/edit', [\App\Http\Controllers\GaleriController::class, 'edit'])->name('galeri.edit');
        Route::put('/galeri/{id}', [\App\Http\Controllers\GaleriController::class, 'update'])->name('galeri.update');
        Route::delete('/galeri/{id}', [\App\Http\Controllers\GaleriController::class, 'destroy'])->name('galeri.destroy');

        Route::resource('/guru', \App\Http\Controllers\GuruController::class);
        Route::get('/guru', [\App\Http\Controllers\GuruController::class, 'index'])->name('guru.index');
        Route::get('/guru/create', [\App\Http\Controllers\GuruController::class, 'create'])->name('guru.create');
        Route::post('/guru', [\App\Http\Controllers\GuruController::class, 'store'])->name('guru.store');
        Route::get('/guru/{id}/edit', [\App\Http\Controllers\GuruController::class, 'edit'])->name('guru.edit');
        Route::put('/guru/{id}', [\App\Http\Controllers\GuruController::class, 'update'])->name('guru.update');
        Route::delete('/guru/{id}', [\App\Http\Controllers\GuruController::class, 'destroy'])->name('guru.destroy');

        Route::resource('/fasilitas', \App\Http\Controllers\FasilitasController::class);
        Route::get('/fasilitas', [\App\Http\Controllers\FasilitasController::class, 'index'])->name('fasilitas.index');
        Route::get('/fasilitas/create', [\App\Http\Controllers\FasilitasController::class, 'create'])->name('fasilitas.create');
        Route::post('/fasilitas', [\App\Http\Controllers\FasilitasController::class, 'store'])->name('fasilitas.store');
        Route::get('/fasilitas/{id}/edit', [\App\Http\Controllers\FasilitasController::class, 'edit'])->name('fasilitas.edit');
        Route::put('/fasilitas/{id}', [\App\Http\Controllers\FasilitasController::class, 'update'])->name('fasilitas.update');
        Route::delete('/fasilitas/{id}', [\App\Http\Controllers\FasilitasController::class, 'destroy'])->name('fasilitas.destroy');

        Route::resource('/tentang', \App\Http\Controllers\TentangController::class);
        Route::get('/tentang', [\App\Http\Controllers\TentangController::class, 'index'])->name('tentang.index');
        Route::get('/tentang/create', [\App\Http\Controllers\TentangController::class, 'create'])->name('tentang.create');
        Route::post('/tentang', [\App\Http\Controllers\TentangController::class, 'store'])->name('tentang.store');
        Route::get('/tentang/{id}/edit', [\App\Http\Controllers\TentangController::class, 'edit'])->name('tentang.edit');
        Route::put('/tentang/{id}', [\App\Http\Controllers\TentangController::class, 'update'])->name('tentang.update');
        Route::delete('/tentang/{id}', [\App\Http\Controllers\TentangController::class, 'destroy'])->name('tentang.destroy');

        Route::resource('/kalender', \App\Http\Controllers\KalenderController::class);
        Route::get('/kalender', [\App\Http\Controllers\KalenderController::class, 'index'])->name('kalender.index');
        Route::get('/kalender/create', [\App\Http\Controllers\KalenderController::class, 'create'])->name('kalender.create');
        Route::post('/kalender', [\App\Http\Controllers\KalenderController::class, 'store'])->name('kalender.store');
        Route::get('/kalender/{id}/edit', [\App\Http\Controllers\KalenderController::class, 'edit'])->name('kalender.edit');
        Route::put('/kalender/{id}', [\App\Http\Controllers\KalenderController::class, 'update'])->name('kalender.update');
        Route::delete('/kalender/{id}', [\App\Http\Controllers\KalenderController::class, 'destroy'])->name('kalender.destroy');

        Route::resource('/ucapankepsek', \App\Http\Controllers\UcapanController::class);
        Route::get('/ucapankepsek', [\App\Http\Controllers\UcapanController::class, 'index'])->name('ucapankepsek.index');
        Route::get('/ucapankepsek/create', [\App\Http\Controllers\UcapanController::class, 'create'])->name('ucapankepsek.create');
        Route::post('/ucapankepsek', [\App\Http\Controllers\UcapanController::class, 'store'])->name('ucapankepsek.store');
        Route::get('/ucapankepsek/{id}/edit', [\App\Http\Controllers\UcapanController::class, 'edit'])->name('ucapankepsek.edit');
        Route::put('/ucapankepsek/{id}', [\App\Http\Controllers\UcapanController::class, 'update'])->name('ucapankepsek.update');
        Route::delete('/ucapankepsek/{id}', [\App\Http\Controllers\UcapanController::class, 'destroy'])->name('ucapankepsek.destroy');

        Route::resource('/visimisi', \App\Http\Controllers\VisimisiController::class);
        Route::get('/visimisi', [\App\Http\Controllers\VisimisiController::class, 'index'])->name('visimisi.index');
        Route::get('/visimisi/create', [\App\Http\Controllers\VisimisiController::class, 'create'])->name('visimisi.create');
        Route::post('/visimisi', [\App\Http\Controllers\VisimisiController::class, 'store'])->name('visimisi.store');
        Route::get('/visimisi/{id}/edit', [\App\Http\Controllers\VisimisiController::class, 'edit'])->name('visimisi.edit');
        Route::put('/visimisi/{id}', [\App\Http\Controllers\VisimisiController::class, 'update'])->name('visimisi.update');
        Route::delete('/visimisi/{id}', [\App\Http\Controllers\VisimisiController::class, 'destroy'])->name('visimisi.destroy');

        Route::resource('/sejarah', \App\Http\Controllers\SejarahController::class);
        Route::get('/sejarah', [\App\Http\Controllers\SejarahController::class, 'index'])->name('sejarah.index');
        Route::get('/sejarah/create', [\App\Http\Controllers\SejarahController::class, 'create'])->name('sejarah.create');
        Route::post('/sejarah', [\App\Http\Controllers\SejarahController::class, 'store'])->name('sejarah.store');
        Route::get('/sejarah/{id}/edit', [\App\Http\Controllers\SejarahController::class, 'edit'])->name('sejarah.edit');
        Route::put('/sejarah/{id}', [\App\Http\Controllers\SejarahController::class, 'update'])->name('sejarah.update');
        Route::delete('/sejarah/{id}', [\App\Http\Controllers\SejarahController::class, 'destroy'])->name('sejarah.destroy');

        Route::resource('/slider', \App\Http\Controllers\SliderController::class);
        Route::get('/slider', [\App\Http\Controllers\SliderController::class, 'index'])->name('slider.index');
        Route::get('/slider/create', [\App\Http\Controllers\SliderController::class, 'create'])->name('slider.create');
        Route::post('/slider', [\App\Http\Controllers\SliderController::class, 'store'])->name('slider.store');
        Route::get('/slider/{id}/edit', [\App\Http\Controllers\SliderController::class, 'edit'])->name('slider.edit');
        Route::put('/slider/{id}', [\App\Http\Controllers\SliderController::class, 'update'])->name('slider.update');
        Route::delete('/slider/{id}', [\App\Http\Controllers\SliderController::class, 'destroy'])->name('slider.destroy');

        Route::resource('/kalender', \App\Http\Controllers\KalenderController::class);
        Route::get('/kalender', [\App\Http\Controllers\KalenderController::class, 'index'])->name('kalender.index');
        Route::get('/kalender/create', [\App\Http\Controllers\KalenderController::class, 'create'])->name('kalender.create');
        Route::post('/kalender', [\App\Http\Controllers\KalenderController::class, 'store'])->name('kalender.store');
        Route::get('/kalender/{id}/edit', [\App\Http\Controllers\KalenderController::class, 'edit'])->name('kalender.edit');
        Route::put('/kalender/{id}', [\App\Http\Controllers\KalenderController::class, 'update'])->name('kalender.update');
        Route::delete('/kalender/{id}', [\App\Http\Controllers\KalenderController::class, 'destroy'])->name('kalender.destroy');

        Route::resource('/profil', \App\Http\Controllers\ProfilController::class);
        Route::get('/profil', [\App\Http\Controllers\ProfilController::class, 'index'])->name('profil.index');
        Route::get('/profil/create', [\App\Http\Controllers\ProfilController::class, 'create'])->name('profil.create');
        Route::post('/profil', [\App\Http\Controllers\ProfilController::class, 'store'])->name('profil.store');
        Route::get('/profil/{id}/edit', [\App\Http\Controllers\ProfilController::class, 'edit'])->name('profil.edit');
        Route::put('/profil/{id}', [\App\Http\Controllers\ProfilController::class, 'update'])->name('profil.update');

app/Http/Controllers/ProfilController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
class ProfilController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = DB::select(DB::raw("select * from profil"));
        return view('profil.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('profil.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_sekolah' => 'required',
            'logo' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'logo_header' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        //upload image
            $logo = $request->file('logo');
            $logo2 = $request->file('logo_header');
            $logo->storeAs('public/profil', $logo->hashName());
            $logo2->storeAs('public/profil', $logo2->hashName());

            DB::insert("INSERT INTO `profil` (`id_profil`, `nama_sekolah`, `logo`, `logo_header`) VALUES (uuid(), ?, ?, ?)",
            [$request->nama_sekolah,$logo->hashName(),$logo2->hashName()]);
            return redirect()->route('profil.index')->with(['success' => 'Data Berhasil Disimpan!']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = DB::table('profil')->where('id_profil', $id)->first();
        return view('profil.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama_sekolah' => 'required',
            'logo' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'logo_header' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);


        //cek update file
        if ($request->file('logo', 'logo_header')) {


            $logo = $request->file('logo');
            $logo2 = $request->file('logo_header');
            $logo->storeAs('public/profil', $logo->hashName());
            $logo2->storeAs('public/profil', $logo2->hashName());


            DB::update(
                "UPDATE `profil` SET `nama_sekolah`=?,`logo`=?,`logo_header`=?  WHERE id_profil=?",
                [$request->nama_sekolah,$logo->hashName(),$logo2->hashName(), $id]
            );
        } else {
            DB::update(
                "UPDATE `profil` SET `nama_sekolah`=? WHERE id_profil=?",
                [$request->nama_sekolah, $id]
            );
        }
        return redirect()->route('profil.index')->with(['success' => 'Data Berhasil Diupdate!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('profil')->where('id_profil', $id)->delete();
        //redirect to index
        return redirect()->route('profil.index')->with(['success' => 'Data Berhasil Dihapus!']);
    }
}

resources/views/profil/create.blade.php
@extends('layouts.app-master')
@section('content')
@auth
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Profil Sekolah</h1>
        <nav>
        <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('layouts.dashboard') }}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('profil.index') }}">Tables</a></li>
                <li class="breadcrumb-item active">Tambah Data</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Tambah Profil Sekolah</h5>
                        <form action="{{ route('profil.store') }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="col-12">
                                <label class="form-label">Nama Sekolah</label>
                                <input type="text" class="form-control @error('nama_sekolah') is-invalid @enderror" name="nama_sekolah" placeholder="Masukkan Nama Sekolah">
                                <!-- error message untuk nama_program -->
                                @error('nama_sekolah')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <br>
                            <div class="col-12">
                                <label class="form-label">Logo</label>
                                <input type="file" class="form-control @error('logo') is-invalid @enderror" name="logo">
                                <!-- error message untuk title -->
                                @error('logo')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <br>
                            <div class="col-12">
                                <label class="form-label">Logo Header</label>
                                <input type="file" class="form-control @error('logo_header') is-invalid @enderror" name="logo_header">
                                <!-- error message untuk title -->
                                @error('logo_header')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <br>
                            <div class="text-center">
                                <button type="submit" class="btn btn-md btn-primary">SIMPAN</button>
                                <button type="reset" class="btn btn-md btn-warning">RESET</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main><!-- End #main -->

@endauth
@endsection

resources/views/profil/edit.blade.php
@extends('layouts.app-master')
@section('content')
@auth
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Data Profil Sekolah</h1>
        <nav>
        <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('layouts.dashboard') }}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('profil.index') }}">Tables</a></li>
                <li class="breadcrumb-item active">Edit Data</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Edit Data Profil Sekolah</h5>
                        <form action="{{ route('profil.update', $data->id_profil) }}" method="post" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="col-12">
                                <label class="form-label">Nama Sekolah</label>
                                <input type="text" class="form-control @error('nama_sekolah') is-invalid @enderror" name="nama_sekolah" placeholder="Masukkan Nama Sekolah" value="{{ $data->nama_sekolah }}">
                                <!-- error message untuk nama_sekolah -->
                                @error('nama_sekolah')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <br>
                            <div class="col-12">
                                <label class="form-label">Logo</label>
                                <input type="file" class="form-control @error('logo') is-invalid @enderror" name="logo">
                                <!-- error message untuk title -->
                                @error('logo')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div> 
                            <br>
                            <div class="col-12">
                                <label class="form-label">Logo Header</label>
                                <input type="file" class="form-control @error('logo_header') is-invalid @enderror" name="logo_header">
                                <!-- error message untuk title -->
                                @error('logo_header')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <br>
                            <div class="text-center">
                                <button type="submit" class="btn btn-md btn-primary">SIMPAN</button>
                                <button type="reset" class="btn btn-md btn-warning">RESET</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main><!-- End #main -->
@endauth
@endsection

resources/views/profil/index.blade.php
@extends('layouts.app-master')

@section('content')
@auth
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Data Profil Sekolah</h1>
        <nav>
        <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('layouts.dashboard') }}">Dashboard</a></li>
                <li class="breadcrumb-item">Tables</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Profil Sekolah</h5>
                        <a href="{{ route('profil.create') }}" class="btn btn-md btn-success mb-3">TAMBAH DATA PROFIL SEKOLAH</a>


                        <!-- Table with stripped rows -->
                        <table class="table datatable">
                            <thead>
                                <tr>
                                    <th>NO</th>
                                    <th>NAMA SEKOLAH</th>
                                    <th>LOGO</th>
                                    <th>LOGO HEADER</th>
                                    <th>AKSI</th>

                                </tr>
                            </thead>
                            <tbody>
                            @php($no = 1)
                                @forelse ($data as $profil)
                                <tr class="text-center">
                                    <td>{{ $no ++ }}</td>

                                    <td>{{ $profil->nama_sekolah}}</td>

                                    <td class="text-center">
                                        <img src="{{Storage::url('public/profil/') . $profil->logo }}" class="rounded" style="width: 150px">

                                    </td>

                                    <td class="text-center">
                                        <img src="{{Storage::url('public/profil/') . $profil->logo_header }}" class="rounded" style="width: 150px">

                                    </td>

                                    <td class="text-center">
                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{route('profil.destroy', $profil->id_profil) }}" method="post">
                                            <a href="{{route('profil.edit', $profil->id_profil) }}" class="btn btn-sm btn-primary">EDIT</a>

                                            @csrf
                                            @method('DELETE')

                                            <button type="submit" class="btn btn-sm btn-danger">HAPUS</button>
                                        </form>
                                    </td>
                                </tr>
                                @empty
                                <div class="alert alert-danger">
                                    Data Profil Sekolah Belum Tersedia.

                                </div>
                                @endforelse
                            </tbody>
                        </table>
                        <!-- End Table with stripped rows -->

                    </div>
                </div>

            </div>
        </div>
    </section>
    <script>
        //message with toastr
        @if(session() -> has('success'))
        toastr.success('{{ session('
            success ') }}', 'BERHASIL!');
        @elseif(session() -> has('error'))
        toastr.error('{{ session('
            error ') }}', 'GAGAL!');
        @endif
    </script>
</main><!-- End #main -->

@endauth
@endsection